source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'MengAutoLayout'

pod 'Masonry', '1.1.0'

pod 'MLCKit/Category', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => 'f20fb29'
pod 'MLCKit/Macro', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => 'f20fb29'
pod 'MLCKit/Proxy', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => 'f20fb29'
