source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'MengAutoLayout'

pod 'Masonry', '1.1.0'

#pod 'SDWebImage'
pod 'SDWebImage', '4.4.6'
#pod 'SDWebImage/WebP'

pod 'YYWebImage', '1.0.5'
