source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'MengAutoLayout'

pod 'Masonry', '1.1.0'

#pod 'SDWebImage'
pod 'SDWebImage', '4.4.6'
#pod 'SDWebImage/WebP'

pod 'YYWebImage', '1.0.5'

pod 'LCText', '0.0.4'

pod 'MLCKit/Category', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '4a5635b'
pod 'MLCKit/Macro', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '4a5635b'
pod 'MLCKit/Proxy', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '4a5635b'
